### ISSUE TITLE
How to visualize the ip_stream_image in rviz2

### ISSUE THREAD

**Issue by reinbja** [pratikPhadte/my_camera#1]
Hi,
I have build your package and was able to visualize my ip camera in the rqt_image_view, but if I add an image visualization in rviz2, I do not receive any images. 

Warning of rviz, see picture

![image](https://github.com/pratikPhadte/my_camera/assets/65226497/c9f8a00f-bc16-484f-a116-db87490fe8ce)

**Comment by pratikPhadte** [comment]
hello, it was due to the quality of service profile, which I have removed. The stream FPS remains the same. i have pushed the repo with changes kindly pull the new version and the issue should be solved. Thanks

**Comment by reinbja** [comment]
Many thanks, now it`s working!
